//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteXReservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClienteXReservacion()
        {
            this.ReservacionXClienteXPaquetes = new HashSet<ReservacionXClienteXPaquete>();
        }
    
        public int idClienteXReservacion { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idReservacion { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Reservacion Reservacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservacionXClienteXPaquete> ReservacionXClienteXPaquetes { get; set; }
    }
}
