//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESeventosEntities1 : DbContext
    {
        public ESeventosEntities1()
            : base("name=ESeventosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrador> Administradors { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ClienteXReservacion> ClienteXReservacions { get; set; }
        public virtual DbSet<Paquete> Paquetes { get; set; }
        public virtual DbSet<PaqueteXCliente> PaqueteXClientes { get; set; }
        public virtual DbSet<PaqueteXProducto> PaqueteXProductoes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Recurso> Recursoes { get; set; }
        public virtual DbSet<RecursoXPaquete> RecursoXPaquetes { get; set; }
        public virtual DbSet<Reservacion> Reservacions { get; set; }
        public virtual DbSet<ReservacionXClienteXPaquete> ReservacionXClienteXPaquetes { get; set; }
        public virtual DbSet<ReservacionXRecurso> ReservacionXRecursoes { get; set; }
    
        public virtual int SP_CrearAdministrador(string usuario, string correo, string cedula, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearAdministrador", usuarioParameter, correoParameter, cedulaParameter, contrasenaParameter);
        }
    
        public virtual int SP_CrearCliente(string usuario, string correo, string cedula, string contrasena)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearCliente", usuarioParameter, correoParameter, cedulaParameter, contrasenaParameter);
        }
    
        public virtual int SP_CrearRecurs(string nombre, string correo, string telefono, string provincia, string tipoRecurso)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var provinciaParameter = provincia != null ?
                new ObjectParameter("provincia", provincia) :
                new ObjectParameter("provincia", typeof(string));
    
            var tipoRecursoParameter = tipoRecurso != null ?
                new ObjectParameter("tipoRecurso", tipoRecurso) :
                new ObjectParameter("tipoRecurso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearRecurs", nombreParameter, correoParameter, telefonoParameter, provinciaParameter, tipoRecursoParameter);
        }
    
        public virtual int SP_CrearRecursoXPaquete(Nullable<int> idRecurso, Nullable<int> idPaquete)
        {
            var idRecursoParameter = idRecurso.HasValue ?
                new ObjectParameter("idRecurso", idRecurso) :
                new ObjectParameter("idRecurso", typeof(int));
    
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("idPaquete", idPaquete) :
                new ObjectParameter("idPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CrearRecursoXPaquete", idRecursoParameter, idPaqueteParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_EncuentraCliente(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_EncuentraCliente", usuarioParameter, passwordParameter);
        }
    
        public virtual ObjectResult<SP_Historial_Reservaciones_Catering_Result> SP_Historial_Reservaciones_Catering()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Historial_Reservaciones_Catering_Result>("SP_Historial_Reservaciones_Catering");
        }
    
        public virtual ObjectResult<SP_Historial_Reservaciones_Cliente_Result> SP_Historial_Reservaciones_Cliente(Nullable<int> idCliente)
        {
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Historial_Reservaciones_Cliente_Result>("SP_Historial_Reservaciones_Cliente", idClienteParameter);
        }
    
        public virtual ObjectResult<SP_Historial_Reservaciones_Decoracion_Result> SP_Historial_Reservaciones_Decoracion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Historial_Reservaciones_Decoracion_Result>("SP_Historial_Reservaciones_Decoracion");
        }
    
        public virtual ObjectResult<SP_Historial_Reservaciones_Local_Result> SP_Historial_Reservaciones_Local()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Historial_Reservaciones_Local_Result>("SP_Historial_Reservaciones_Local");
        }
    
        public virtual ObjectResult<SP_Historial_Reservaciones_Musica_Result> SP_Historial_Reservaciones_Musica()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Historial_Reservaciones_Musica_Result>("SP_Historial_Reservaciones_Musica");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Login_Administrador(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Login_Administrador", usuarioParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_Login_Cliente(string usuario, string password)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Login_Cliente", usuarioParameter, passwordParameter);
        }
    
        public virtual int SP_RealizarReservacion(string numReservacion, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, string descripcion, Nullable<int> idPaquete)
        {
            var numReservacionParameter = numReservacion != null ?
                new ObjectParameter("numReservacion", numReservacion) :
                new ObjectParameter("numReservacion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("hora", hora) :
                new ObjectParameter("hora", typeof(System.TimeSpan));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var idPaqueteParameter = idPaquete.HasValue ?
                new ObjectParameter("idPaquete", idPaquete) :
                new ObjectParameter("idPaquete", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RealizarReservacion", numReservacionParameter, fechaParameter, horaParameter, descripcionParameter, idPaqueteParameter);
        }
    
        public virtual int SP_RegistrarPaquete(Nullable<int> idRecurso, string nombre, Nullable<decimal> precio)
        {
            var idRecursoParameter = idRecurso.HasValue ?
                new ObjectParameter("idRecurso", idRecurso) :
                new ObjectParameter("idRecurso", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_RegistrarPaquete", idRecursoParameter, nombreParameter, precioParameter);
        }
    
        public virtual int SP_Reservacion_Final(Nullable<int> idReservacion, Nullable<int> idRecurso, Nullable<int> idCliente)
        {
            var idReservacionParameter = idReservacion.HasValue ?
                new ObjectParameter("idReservacion", idReservacion) :
                new ObjectParameter("idReservacion", typeof(int));
    
            var idRecursoParameter = idRecurso.HasValue ?
                new ObjectParameter("idRecurso", idRecurso) :
                new ObjectParameter("idRecurso", typeof(int));
    
            var idClienteParameter = idCliente.HasValue ?
                new ObjectParameter("idCliente", idCliente) :
                new ObjectParameter("idCliente", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_Reservacion_Final", idReservacionParameter, idRecursoParameter, idClienteParameter);
        }
    
        public virtual ObjectResult<SP_VerRecursos_Result> SP_VerRecursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VerRecursos_Result>("SP_VerRecursos");
        }
    }
}
