//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eventos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservacionXClienteXPaquete
    {
        public int idReservacionXClienteXPaquete { get; set; }
        public Nullable<int> idReservacionXCliente { get; set; }
        public Nullable<int> idPaquete { get; set; }
    
        public virtual ClienteXReservacion ClienteXReservacion { get; set; }
        public virtual Paquete Paquete { get; set; }
    }
}
